# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miracle_razee/code_files/opengl/theatre-opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miracle_razee/code_files/opengl/theatre-opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miracle_razee/code_files/opengl/theatre-opengl/CMakeFiles /home/miracle_razee/code_files/opengl/theatre-opengl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miracle_razee/code_files/opengl/theatre-opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named theatre

# Build rule for target.
theatre: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 theatre
.PHONY : theatre

# fast build rule for target.
theatre/fast:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/build
.PHONY : theatre/fast

src/chair.o: src/chair.cpp.o

.PHONY : src/chair.o

# target to build an object file
src/chair.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.o
.PHONY : src/chair.cpp.o

src/chair.i: src/chair.cpp.i

.PHONY : src/chair.i

# target to preprocess a source file
src/chair.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.i
.PHONY : src/chair.cpp.i

src/chair.s: src/chair.cpp.s

.PHONY : src/chair.s

# target to generate assembly for a file
src/chair.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.s
.PHONY : src/chair.cpp.s

src/chairarm.o: src/chairarm.cpp.o

.PHONY : src/chairarm.o

# target to build an object file
src/chairarm.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.o
.PHONY : src/chairarm.cpp.o

src/chairarm.i: src/chairarm.cpp.i

.PHONY : src/chairarm.i

# target to preprocess a source file
src/chairarm.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.i
.PHONY : src/chairarm.cpp.i

src/chairarm.s: src/chairarm.cpp.s

.PHONY : src/chairarm.s

# target to generate assembly for a file
src/chairarm.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.s
.PHONY : src/chairarm.cpp.s

src/fan.o: src/fan.cpp.o

.PHONY : src/fan.o

# target to build an object file
src/fan.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/fan.cpp.o
.PHONY : src/fan.cpp.o

src/fan.i: src/fan.cpp.i

.PHONY : src/fan.i

# target to preprocess a source file
src/fan.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/fan.cpp.i
.PHONY : src/fan.cpp.i

src/fan.s: src/fan.cpp.s

.PHONY : src/fan.s

# target to generate assembly for a file
src/fan.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/fan.cpp.s
.PHONY : src/fan.cpp.s

src/stair.o: src/stair.cpp.o

.PHONY : src/stair.o

# target to build an object file
src/stair.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.o
.PHONY : src/stair.cpp.o

src/stair.i: src/stair.cpp.i

.PHONY : src/stair.i

# target to preprocess a source file
src/stair.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.i
.PHONY : src/stair.cpp.i

src/stair.s: src/stair.cpp.s

.PHONY : src/stair.s

# target to generate assembly for a file
src/stair.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.s
.PHONY : src/stair.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

theatre.o: theatre.cpp.o

.PHONY : theatre.o

# target to build an object file
theatre.cpp.o:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.o
.PHONY : theatre.cpp.o

theatre.i: theatre.cpp.i

.PHONY : theatre.i

# target to preprocess a source file
theatre.cpp.i:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.i
.PHONY : theatre.cpp.i

theatre.s: theatre.cpp.s

.PHONY : theatre.s

# target to generate assembly for a file
theatre.cpp.s:
	$(MAKE) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.s
.PHONY : theatre.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... theatre"
	@echo "... src/chair.o"
	@echo "... src/chair.i"
	@echo "... src/chair.s"
	@echo "... src/chairarm.o"
	@echo "... src/chairarm.i"
	@echo "... src/chairarm.s"
	@echo "... src/fan.o"
	@echo "... src/fan.i"
	@echo "... src/fan.s"
	@echo "... src/stair.o"
	@echo "... src/stair.i"
	@echo "... src/stair.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... theatre.o"
	@echo "... theatre.i"
	@echo "... theatre.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

